### ISSUE TITLE
Event Propagation

### ISSUE THREAD

**Issue by load0ne** [naver/egjs-component#44]
there are suggestion that is event propagation.
It is not absolutely necessary, but I think it would be good to apply.

First, let me share my experience.
the experience was limited to UI development.

i think the UI has a hierarchical structure in general, whether it is physical or conceptual.
so when i applied this component to UI, events also had to be designed to follow the hierarchy.

when, i designed to
```none
SearchPage (independent component)
   ㄴ SearchInput
   ㄴ Filter
   ㄴ Category
```

the event structure was as follow,
```typescript
SearchPage (independent) - onSubmit, onClear, onFilter, onSort,...
   ㄴ SearchInput - onSubmit, onClear
   ㄴ Filter - onFilter
   ㄴ Sort - onSort
```

and implemented this as below.

```typescript
class SearchPage extends eg.Component {
    constructor() {
        super();
        this.context = {};
        this.searchInput = new SearchInput(); // child component
        this.filter = new Filter();  // child component
        // intercepts event
        this.searchInput.on('submit', (event) => {
            // bubbling
            event.pageContext = context;
            this.trigger(event.eventType, event)
        });
    }
}

const searchPage = new SearchPage();

searchPage.on('submit', (event) => {
    // todo - external module
})
```

but I thought it would be better if the component itself provided it systematically.
because the deeper the component, the more it will equal callback hell.

thanks for reading.

**Comment by mixed** [comment]
Thank you for your suggestion. I think that It is good feature. We will try to think more about the feature and let you know again. :)
